-- V2: Insert initial stock price data
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (102, 'BHEL', 43.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (103, 'HDFC', 1400.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (104, 'HCL', 950.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (105, 'TCS', 2950.00);

