-- Insert sample stock price data (ON CONFLICT DO NOTHING prevents duplicate errors on restart)
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (102, 'BHEL', 43.00) ON CONFLICT DO NOTHING;
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (103, 'HDFC', 1400.00) ON CONFLICT DO NOTHING;
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (104, 'HCL', 950.00) ON CONFLICT DO NOTHING;
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUES (105, 'TCS', 2950.00) ON CONFLICT DO NOTHING;

