package com.springboot.webmvc.passing.data.by.differentway.from.UI.to.Server.service;

import com.springboot.webmvc.passing.data.by.differentway.from.UI.to.Server.Respository.ProductRespository;
import com.springboot.webmvc.passing.data.by.differentway.from.UI.to.Server.pojo.Product;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ProductService {
   @Autowired
   private ProductRespository productRespository;
   
   @Transactional(rollbackFor = Exception.class)
    public void saveProductDetailsToDb(Product product){
        try {
            // Always set productId to null for new entities (auto-generated by sequence)
            // This prevents merge conflicts - Spring Data JPA's save() will merge if ID exists
            // By forcing it to null, we ensure it's treated as a new entity
            product.setProductId(null);
            System.out.println("Saving product: " + product);
            
            // Use saveAndFlush to ensure the insert is executed and committed immediately
            Product savedProduct = productRespository.saveAndFlush(product);
            System.out.println("Product saved successfully with ID: " + savedProduct.getProductId());
            
        } catch (Exception e) {
            System.err.println("Error saving product: " + e.getMessage());
            e.printStackTrace();
            throw e; // Re-throw to ensure transaction rollback
        }
    }
}
